[accounts.main]
default = true
email = "jhk06@mailbox.org"
backend.type = "notmuch"
backend.dp-path = "~/mail"
folder.aliases.inbox = "Inbox"

# SMTP
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.mailbox.org"
message.send.backend.port = 465
message.send.backend.login = "jhk06@mailbox.org"
message.send.backend.auth.type = "password"
message.send.backend.auth.cmd = "pass show mail/mailbox.org | head -n 1"

envelope.list.table.id-color = "blue"
envelope.list.table.date-color = "magenta"
