#!/usr/bin/env bash

# execute a window with rules
# two options:
#   class: a bit more cumbersome and does not work for x11 processes
#   pid: logical, but wont work for applications that spawn more than one window in the same process

if [[ "$1" == class ]]; then
    CLASS="$2"
    $3 &
    swaymsg -t subscribe '["window"]' --monitor |
        jq --unbuffered --arg class "$CLASS" 'select(.change == "new" and .container.app_id == $class)|.container.id, halt' | {
        read -r id
        swaymsg "[con_id=$id] $4"
    }
elif [[ "$1" == pid ]]; then
    $2 &
    pid=$!
    swaymsg -t subscribe '["window"]' --monitor |
        jq --unbuffered --argjson pid "$pid" 'select(.change == "new" and .container.pid == $pid)|.container.id, halt' | {
        read -r id
        swaymsg "[con_id=$id] $3"
    }
fi
