#!/usr/bin/env bash

# execute a window with rules
# $1: type:
#   class: a bit more cumbersome, takes another argument
#   pid: logical, but wont work for applications that spawn more than one window in the same process
# $2: command
# $3: 1st rule: swaymsg command, run with [con_id=$id]
# ${@:4} 2nd rule: shell command, every %p is replaced by the pid

case "$1" in
--class)
    PREDICATE="(.container.app_id == \"$2\" or .container.class == \"$2\")"
    $3 &
    disown
    pid=$!
    shift 3
    ;;
--pid)
    $2 &
    disown
    pid=$!
    PREDICATE=".container.pid == $pid"
    shift 2
    ;;
esac

sway_cmd="$1"
shift
declare -a command
for word in "$@"; do
    command+=("${word//%p/$pid}")
done

swaymsg -t subscribe '["window"]' -- monitor | jq --unbuffered "select(.change == \"new\" and $PREDICATE)|.container.id, halt" | {
    read -r id
    sleep 0.1
    swaymsg "[con_id=$id] $sway_cmd"
    if ((${#command} > 0)); then
        "${command[@]}"
    fi
}
