classic: false
blocks:
  - user
  - permission
  - date
  - name
color:
  when: always
  theme: custom
date: '+%b %d'
icons:
  when: never
sorting:
  dir-grouping: first
symlink-arrow: ->
size: short
