classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
color:
  when: always
  theme: custom
date: '+%H:%M %d/%m/%y'
icons:
  when: always
  seperator: " "
sorting:
    dir-grouping: first
symlink-arrow: ->
size: short
