#!/usr/bin/env zsh

active_pid="$(hyprctl -j activewindow|jq '.pid')"

clients=($(pactl --format=json list sink-inputs \
    | jq --arg pid "$active_pid" '.[]|select(.properties."application.process.id" == $pid).index'))

if [[ "$clients" != "" ]] {
    for client in "${clients[@]}"; do
        pactl set-sink-input-mute "$client" toggle
    done
}
