#!/usr/bin/env bash

active_pid="$(hyprctl -j activewindow|jq '.pid')"

read -ra clients < <(
    pactl --format=json list sink-inputs \
    | jq --arg pid "$active_pid" \
    '.[]|select(.properties."application.process.id" == $pid).index'
)

if [[ "$clients" != "" ]]; then
    for client in "${clients[@]}"; do
        pactl set-sink-input-mute "$client" toggle
    done
fi
