#!/usr/bin/env zsh

active_pid="$(hyprctl -j activewindow|jq '.pid')"

client="$(pactl --format=json list sink-inputs \
    | jq --arg pid "$active_pid" '.[]|select(.properties."application.process.id" == $pid).index')"

if [[ "$client" != "" ]] {
    pactl set-sink-input-mute "$client" toggle
}
