#!/usr/bin/env zsh

word="$1"

IFS=$'\n' devices=($(pactl --format=json list ${word}s|jq '.[].name' -r))
current="$(pactl get-default-${word})"
num_devices="${#devices}"

cmd="${2:-next}"

for ((i=1; i <= $num_devices; i++)) {
    if [[ "${devices[i]}" == "$current" ]] {
        if [[ "$cmd" == "next" ]] {
            if ((i == num_devices)); then
                pactl set-default-$word "${devices[1]}"
            else
                pactl set-default-$word "${devices[i+1]}"
            fi
        } else {
            if ((i == 1)); then
                pactl set-default-$word "${devices[-1]}"
            else
                pactl set-default-$word "${devices[i-1]}"
            fi
        }
        break
    }
}
