#!/usr/bin/env python

import sys
import os
import code
from colorama import Fore, Back, Style

ver = f"{sys.version_info.major}.{sys.version_info.minor}"


class DmxRepl(code.InteractiveConsole):
    def __init__(self):
        super().__init__(locals=None)
        sys.ps1 = f"{Style.BRIGHT}{Fore.BLUE}{Fore.BLACK + Back.BLUE}󰌠 {ver}{Fore.BLUE}{Back.RESET}{Style.RESET_ALL} "
    def cmdloop(self, intro=None):
        super().cmdloop(intro)
        print("hi")

if __name__ == "__main__":
    cons = DmxRepl()
    cons.interact(banner=None)
